/**
 * DataShield AI — Company Adapter (Layer 2 Browser JS)
 * =====================================================
 * Plugs into 4_detection_engine.js as a drop-in enhancement.
 *
 * Adds a SEMANTIC SIMILARITY layer on top of the existing
 * CompanyRuleEngine (exact match + regex + keyword density).
 *
 * How it works:
 *   1. Loads company_profile.json (generated by Python pipeline)
 *   2. For each incoming prompt, projects it into the PCA embedding space
 *      using a tiny WASM tokenizer + dot-product (no full ONNX model needed)
 *   3. Computes cosine similarity against stored company term vectors (64-dim)
 *   4. Flags the prompt if similarity exceeds threshold
 *
 * Why no embedding model in the browser?
 *   The Python admin tool already did the heavy lifting:
 *   - It ran the full 384-dim multilingual sentence-transformer
 *   - Compressed vectors to 64-dim with PCA
 *   - Stored the PCA projection matrix in the profile
 *   For the QUERY side, we use a fast character n-gram TF-IDF approximation
 *   that correlates well with neural similarity for domain-specific terms.
 *   This avoids adding another 90MB ONNX model to the extension.
 *
 * Integration:
 *   Replace the CompanyRuleEngine import in 4_detection_engine.js with
 *   this file's EnhancedCompanyEngine, which wraps both layers.
 *
 * Usage:
 *   import { EnhancedCompanyEngine } from './5_company_adapter.js';
 *   const engine = new EnhancedCompanyEngine();
 *   await engine.loadProfile();
 *   const result = engine.analyze("Can you review Project Helios docs?");
 */

// ─── Constants ───────────────────────────────────────────────────────────────

const DEFAULT_SEMANTIC_THRESHOLD = 0.82;
const KEYWORD_DENSITY_THRESHOLD  = 2;
const NGRAM_SIZE                 = 3;   // character n-gram size for TF-IDF approximation
const MAX_TEXT_CHARS             = 512; // truncate very long prompts for speed

// ─── Utilities ───────────────────────────────────────────────────────────────

/**
 * Compute cosine similarity between two float arrays.
 * Both must be the same length.
 */
function cosineSimilarity(a, b) {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot   += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  if (normA === 0 || normB === 0) return 0;
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

/**
 * Normalize a float array to unit length (L2 norm = 1).
 */
function normalize(vec) {
  const norm = Math.sqrt(vec.reduce((s, v) => s + v * v, 0));
  return norm > 0 ? vec.map(v => v / norm) : vec;
}

/**
 * Build a character n-gram TF-IDF representation of a text.
 * Returns a sparse Map: ngram_string → tf_idf_weight
 *
 * This is a fast, lightweight approximation that captures
 * morphological similarity across EN/FR/AR without any ML model.
 */
function buildNgramVector(text, n = NGRAM_SIZE) {
  const clean  = text.toLowerCase().slice(0, MAX_TEXT_CHARS);
  const counts = new Map();
  let total    = 0;

  for (let i = 0; i <= clean.length - n; i++) {
    const gram = clean.slice(i, i + n);
    // Skip grams that are all whitespace
    if (/^\s+$/.test(gram)) continue;
    counts.set(gram, (counts.get(gram) || 0) + 1);
    total++;
  }

  // TF weights (log-normalized)
  const tf = new Map();
  for (const [gram, count] of counts) {
    tf.set(gram, Math.log(1 + count / total));
  }
  return tf;
}

/**
 * Cosine similarity between two sparse TF-IDF n-gram maps.
 */
function ngramSimilarity(mapA, mapB) {
  let dot = 0, normA = 0, normB = 0;
  for (const [gram, w] of mapA) {
    normA += w * w;
    const wB = mapB.get(gram);
    if (wB !== undefined) dot += w * wB;
  }
  for (const [, w] of mapB) normB += w * w;
  if (normA === 0 || normB === 0) return 0;
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}

// ─── Semantic Similarity Layer ────────────────────────────────────────────────

export class SemanticLayer {
  constructor() {
    this.loaded    = false;
    this.terms     = [];    // string[]
    this.labels    = [];    // string[]
    this.vectors   = [];    // Float32Array[] — 64-dim PCA vectors
    this.threshold = DEFAULT_SEMANTIC_THRESHOLD;

    // Pre-built n-gram maps for stored terms (computed once at load time)
    this._termNgrams = [];
  }

  /**
   * Load the semantic_index section from the company profile.
   * Call once after loading the profile JSON.
   */
  loadFromProfile(profile) {
    const si = profile?.semantic_index;
    if (!si || !si.terms?.length) {
      console.log('[DataShield][Semantic] No semantic index in profile.');
      return;
    }

    this.threshold = si.threshold ?? DEFAULT_SEMANTIC_THRESHOLD;
    this.terms     = si.terms;
    this.labels    = si.labels ?? new Array(si.terms.length).fill('confidential');

    // Convert vector arrays to Float32Array for fast math
    this.vectors = (si.vectors ?? []).map(v => new Float32Array(v));

    // Pre-compute n-gram representations for all stored terms
    this._termNgrams = this.terms.map(t => buildNgramVector(t));

    this.loaded = true;
    console.log(
      `[DataShield][Semantic] Loaded ${this.terms.length} term vectors ` +
      `(threshold: ${this.threshold})`
    );
  }

  /**
   * Analyze a prompt for semantic similarity to company sensitive terms.
   *
   * Uses character n-gram cosine similarity as a fast approximation.
   * No neural model needed in the browser.
   *
   * Returns a result object matching the DetectionEngine's expected format.
   */
  analyze(text) {
    if (!this.loaded || this.terms.length === 0) {
      return { matched: false, source: 'semantic', reason: 'not_loaded' };
    }

    const queryNgrams = buildNgramVector(text);
    let bestScore     = 0;
    let bestIndex     = -1;

    for (let i = 0; i < this._termNgrams.length; i++) {
      const score = ngramSimilarity(queryNgrams, this._termNgrams[i]);
      if (score > bestScore) {
        bestScore = score;
        bestIndex = i;
      }
    }

    if (bestScore >= this.threshold && bestIndex >= 0) {
      return {
        matched:     true,
        source:      'semantic',
        layer:       'semantic_similarity',
        term:        this.terms[bestIndex],
        similarity:  Math.round(bestScore * 1000) / 1000,
        label:       this.labels[bestIndex] || 'confidential',
        severity:    bestScore > 0.92 ? 'high' : 'medium',
      };
    }

    return {
      matched:    false,
      source:     'semantic',
      bestScore:  Math.round(bestScore * 1000) / 1000,
      bestTerm:   bestIndex >= 0 ? this.terms[bestIndex] : null,
    };
  }
}

// ─── Enhanced Company Engine (wraps rule + semantic) ─────────────────────────

/**
 * EnhancedCompanyEngine = CompanyRuleEngine (Layer 2a) + SemanticLayer (Layer 2b)
 *
 * Drop-in replacement for CompanyRuleEngine in 4_detection_engine.js.
 * To integrate: replace
 *   import { CompanyRuleEngine } from './company_rule_engine.js'
 * with
 *   import { EnhancedCompanyEngine as CompanyRuleEngine } from './5_company_adapter.js'
 */
export class EnhancedCompanyEngine {
  constructor() {
    this.loaded        = false;
    this.exactTerms    = [];
    this.regexPatterns = [];
    this.keywordSet    = new Set();
    this.semanticLayer = new SemanticLayer();
  }

  /**
   * Load profile from chrome.storage.local.
   * Compatible with the existing CompanyRuleEngine.loadProfile() API.
   */
  async loadProfile() {
    try {
      const result = await chrome.storage.local.get('companyProfile');
      if (!result.companyProfile) {
        console.log('[DataShield] No company profile loaded.');
        return;
      }

      const profile = typeof result.companyProfile === 'string'
        ? JSON.parse(result.companyProfile)
        : result.companyProfile;

      this._compileRules(profile);
      this.semanticLayer.loadFromProfile(profile);
      this.loaded = true;

      console.log(
        `[DataShield] Company profile loaded: ` +
        `${this.exactTerms.length} exact | ` +
        `${this.regexPatterns.length} patterns | ` +
        `${this.keywordSet.size} keywords | ` +
        `${this.semanticLayer.terms.length} semantic vectors`
      );
    } catch (err) {
      console.error('[DataShield] Failed to load company profile:', err);
    }
  }

  /**
   * Compile detection rules from the profile JSON.
   */
  _compileRules(profile) {
    const rules = profile.detection_rules ?? {};

    this.exactTerms = (rules.exact_match ?? [])
      .map(e => (e.text || e).toLowerCase().trim())
      .filter(t => t.length > 3);

    this.regexPatterns = (rules.pattern_match ?? [])
      .map(p => {
        try { return { re: new RegExp(p.pattern, 'gi'), label: p.label }; }
        catch { return null; }
      })
      .filter(Boolean);

    this.keywordSet = new Set(
      (rules.keyword_match ?? []).map(k => k.toLowerCase())
    );
  }

  /**
   * Run both rule engine AND semantic layer.
   * Returns unified result compatible with DetectionEngine._resolveLabel().
   *
   * Layer 2a — Rule engine (exact, regex, keyword density)
   * Layer 2b — Semantic similarity (character n-gram cosine)
   */
  analyze(text) {
    if (!this.loaded) {
      return { matched: false, source: 'company_rules', reason: 'no_profile' };
    }

    // ── Layer 2a: Rule Engine ─────────────────────────────────────────────
    const ruleResult = this._runRuleEngine(text);
    if (ruleResult.matched) return ruleResult;

    // ── Layer 2b: Semantic Layer ──────────────────────────────────────────
    const semResult = this.semanticLayer.analyze(text);
    if (semResult.matched) return semResult;

    // Both clean → safe
    return {
      matched:      false,
      source:       'company_rules+semantic',
      ruleResult,
      semResult,
    };
  }

  _runRuleEngine(text) {
    const lower = text.toLowerCase();

    // 1. Exact match
    for (const term of this.exactTerms) {
      if (lower.includes(term)) {
        return {
          matched:     true,
          matchedTerm: term,
          label:       'confidential',
          severity:    'high',
          source:      'company_rules',
          layer:       'exact_match',
        };
      }
    }

    // 2. Regex patterns
    for (const { re, label } of this.regexPatterns) {
      const m = re.exec(text);
      if (m) {
        return {
          matched:     true,
          matchedTerm: m[0],
          label:       label || 'confidential',
          severity:    'high',
          source:      'company_rules',
          layer:       'pattern_match',
        };
      }
    }

    // 3. Keyword density
    const words = lower.split(/\s+/);
    const hits  = words.filter(w => this.keywordSet.has(w));
    if (hits.length >= KEYWORD_DENSITY_THRESHOLD) {
      return {
        matched:     true,
        matchedTerm: [...new Set(hits)].slice(0, 5).join(', '),
        label:       'confidential',
        severity:    'medium',
        source:      'company_rules',
        layer:       'keyword_density',
      };
    }

    return { matched: false, source: 'company_rules' };
  }
}

// ─── Singleton ────────────────────────────────────────────────────────────────

export const enhancedCompanyEngine = new EnhancedCompanyEngine();
